name: Build Plugin JAR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Rename JAR to soulbind-smp-{version}.jar
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          mv target/*.jar target/soulbind-smp-$VERSION.jar

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: soulbind-smp
          path: target/soulbind-smp-*.jar
